# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professorrating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='rmp_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
