# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professorrating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='classrating',
            name='rating',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='professor',
            name='average_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='number_of_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
