# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professorrating', '0002_auto_20170331_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrating',
            name='number_rating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
