# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
