# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 21:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='common_classes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
