# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorroadmaps',
            name='road_map',
            field=models.TextField(),
        ),
    ]
