# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 03:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20170410_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorroadmaps',
            name='road_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
